import{a as S,S as E,i as n}from"./assets/vendor-DqB7j7Ix.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const h of s.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&u(h)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function u(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const O="50757897-a80a694250436cdde2013620b",P="https://pixabay.com/api/",q=15;async function f(o,e){const r={key:O,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:q};return(await S.get(P,{params:r})).data}const p=document.querySelector(".gallery"),y=document.querySelector(".loader"),a=document.querySelector(".load-more"),R=new E(".gallery a");function g(o){const e=o.map(r=>`
    <li class="gallery-item">
      <a href="${r.largeImageURL}">
        <img src="${r.webformatURL}" alt="${r.tags}" />
      </a>
      <div class="info">
        <p><b>Likes</b> ${r.likes}</p>
        <p><b>Views</b> ${r.views}</p>
        <p><b>Comments</b> ${r.comments}</p>
        <p><b>Downloads</b> ${r.downloads}</p>
      </div>
    </li>
  `).join("");p.insertAdjacentHTML("beforeend",e),R.refresh()}function C(){p.innerHTML=""}function L(){y.classList.remove("hidden")}function b(){y.classList.add("hidden")}function w(){a.classList.remove("hidden"),a.disabled=!1,a.textContent="Load more"}function c(){a.classList.add("hidden")}const v=document.querySelector(".form"),B=v.querySelector('input[name="search-text"]'),$=document.querySelector(".load-more");document.querySelector(".loader");let l="",d=1,m=0,i=0;v.addEventListener("submit",async o=>{if(o.preventDefault(),l=B.value.trim(),d=1,i=0,!l){n.warning({message:"Please enter a search term.",closeOnClick:!0,position:"topRight"});return}C(),c(),L();try{const e=await f(l,d);if(m=e.totalHits,e.hits.length===0){n.info({message:"Sorry, there are no images matching your search query. Please try again!",closeOnClick:!0,position:"topRight"});return}g(e.hits),i+=e.hits.length,i<m?w():(c(),n.info({message:"We're sorry, but you've reached the end of search results.",closeOnClick:!0,position:"topRight"}))}catch(e){n.error({message:"Something went wrong. Please try again later.",closeOnClick:!0,position:"topRight"}),console.error(e)}finally{b()}});$.addEventListener("click",async()=>{c(),L(),await new Promise(o=>setTimeout(o,1e3));try{d+=1;const o=await f(l,d);g(o.hits),i+=o.hits.length,i>=m?(c(),n.info({message:"We're sorry, but you've reached the end of search results.",closeOnClick:!0,position:"topRight"})):w();const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}catch(o){n.error({message:"Failed to load more images.",closeOnClick:!0,position:"topRight"}),console.error(o)}finally{b()}});
//# sourceMappingURL=index.js.map
